name: stats

on:
  schedule:
    - cron: '0 0 * * 1' 
  push:
    branches: [main]
      
 

jobs:
  build:
    runs-on: ubuntu latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update
          commit_user_name: Jorge Leon [Github Actions]
          commit_user_email: crashe24@hotmail.com
          commit_author: Jorge Leon Crashe24
      
    
  
